//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DellyShopApp.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DellyShopApp.Languages.AppResources.ar", typeof(AppResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        internal static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string BestSeller {
            get {
                return ResourceManager.GetString("BestSeller", resourceCulture);
            }
        }
        
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        internal static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        internal static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        internal static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        internal static string NotificatinTitle {
            get {
                return ResourceManager.GetString("NotificatinTitle", resourceCulture);
            }
        }
        
        internal static string NotificationSubtitle {
            get {
                return ResourceManager.GetString("NotificationSubtitle", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string PreviousViewed {
            get {
                return ResourceManager.GetString("PreviousViewed", resourceCulture);
            }
        }
        
        internal static string ProcutTitle {
            get {
                return ResourceManager.GetString("ProcutTitle", resourceCulture);
            }
        }
        
        internal static string ProcutTitle1 {
            get {
                return ResourceManager.GetString("ProcutTitle1", resourceCulture);
            }
        }
        
        internal static string ProcutTitle2 {
            get {
                return ResourceManager.GetString("ProcutTitle2", resourceCulture);
            }
        }
        
        internal static string ProcutTitle3 {
            get {
                return ResourceManager.GetString("ProcutTitle3", resourceCulture);
            }
        }
        
        internal static string ProductBrand {
            get {
                return ResourceManager.GetString("ProductBrand", resourceCulture);
            }
        }
        
        internal static string ProductBrand1 {
            get {
                return ResourceManager.GetString("ProductBrand1", resourceCulture);
            }
        }
        
        internal static string ProductBrand2 {
            get {
                return ResourceManager.GetString("ProductBrand2", resourceCulture);
            }
        }
        
        internal static string ProductBrand3 {
            get {
                return ResourceManager.GetString("ProductBrand3", resourceCulture);
            }
        }
        
        internal static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        internal static string TitleDesc {
            get {
                return ResourceManager.GetString("TitleDesc", resourceCulture);
            }
        }
        
        internal static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        internal static string MyBasket {
            get {
                return ResourceManager.GetString("MyBasket", resourceCulture);
            }
        }
        
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        internal static string SelectCreditCard {
            get {
                return ResourceManager.GetString("SelectCreditCard", resourceCulture);
            }
        }
        
        internal static string ShippingCost {
            get {
                return ResourceManager.GetString("ShippingCost", resourceCulture);
            }
        }
        
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        internal static string AddBasket {
            get {
                return ResourceManager.GetString("AddBasket", resourceCulture);
            }
        }
        
        internal static string AddCreditCard {
            get {
                return ResourceManager.GetString("AddCreditCard", resourceCulture);
            }
        }
        
        internal static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        internal static string AddressDetail {
            get {
                return ResourceManager.GetString("AddressDetail", resourceCulture);
            }
        }
        
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        internal static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        internal static string DarkThemeEnabled {
            get {
                return ResourceManager.GetString("DarkThemeEnabled", resourceCulture);
            }
        }
        
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        internal static string EnableNotification {
            get {
                return ResourceManager.GetString("EnableNotification", resourceCulture);
            }
        }
        
        internal static string ExampleHomeAddress {
            get {
                return ResourceManager.GetString("ExampleHomeAddress", resourceCulture);
            }
        }
        
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        internal static string LastView {
            get {
                return ResourceManager.GetString("LastView", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string LoremComment {
            get {
                return ResourceManager.GetString("LoremComment", resourceCulture);
            }
        }
        
        internal static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        internal static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        internal static string NotificationDetail {
            get {
                return ResourceManager.GetString("NotificationDetail", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        internal static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        internal static string Product_Detail {
            get {
                return ResourceManager.GetString("Product Detail", resourceCulture);
            }
        }
        
        internal static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        internal static string SelectStreet {
            get {
                return ResourceManager.GetString("SelectStreet", resourceCulture);
            }
        }
        
        internal static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string ShowMoreDetail {
            get {
                return ResourceManager.GetString("ShowMoreDetail", resourceCulture);
            }
        }
        
        internal static string SortType {
            get {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }
        
        internal static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        internal static string SuccessOrder {
            get {
                return ResourceManager.GetString("SuccessOrder", resourceCulture);
            }
        }
        
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        internal static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
        
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        internal static string PackingStage {
            get {
                return ResourceManager.GetString("PackingStage", resourceCulture);
            }
        }
        
        internal static string AddNewAddress {
            get {
                return ResourceManager.GetString("AddNewAddress", resourceCulture);
            }
        }
        
        internal static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        internal static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string EnterEmailAddress {
            get {
                return ResourceManager.GetString("EnterEmailAddress", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string SuccessSendEmail {
            get {
                return ResourceManager.GetString("SuccessSendEmail", resourceCulture);
            }
        }
        
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        internal static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        internal static string AddedBakset {
            get {
                return ResourceManager.GetString("AddedBakset", resourceCulture);
            }
        }
        
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        internal static string ScanCard {
            get {
                return ResourceManager.GetString("ScanCard", resourceCulture);
            }
        }
    }
}
